name: hubia
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+9

environment:
  sdk: '>=3.4.0-99.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.7
  percent_indicator: ^4.2.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.0.0
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.4
  go_router: ^13.2.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.7.0
  flutter_webview_pro: ^3.0.1+4
  share_plus: ^7.2.2
  mailto: ^2.0.0
  device_info_plus: ^9.1.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  hooks_riverpod: ^2.4.10
  google_mobile_ads: ^1.2.0
  flutter_dialogs: ^3.0.0
  flutter_inappwebview: ^5.8.0
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.7
  flutter_file_downloader: ^1.2.1
  android_path_provider: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_mixto.png
