import 'package:hubia/screens/screens_barril.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'dart:math';

class DatabaseHandlerIA {
  Future<Database> initializeDB() async {
    String path = await getDatabasesPath();
    return openDatabase(
      join(path, 'ias_32.db'),
      onCreate: (database, version) async {
        const String createIaTable = ''
            'CREATE TABLE access_ia ('
            ' id INTEGER PRIMARY KEY AUTOINCREMENT,'
            ' name TEXT,'
            ' category TEXT,'
            ' imageUrl TEXT,'
            ' webUrl TEXT,'
            ' entornoEjecucion TEXT,'
            ' description TEXT,'
            ' tutorialUrl TEXT'
            ');';

        await database.execute(createIaTable);

        const String createFavoritesTable = ''
            'CREATE TABLE favorite_ias ('
            ' name TEXT PRIMARY KEY'
            ');';

        await database.execute(createFavoritesTable);

        //images
        //\n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano.

        // video ---
        //tecogan

        // audio ---
        //

        // texto ---
        //perplexi: es una plataforma que combina las capacidades de un buscador conversacional con inteligencia artificial generativa. Utiliza modelos de lenguaje avanzados para proporcionar respuestas precisas a preguntas complejas.  \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano.https://www.perplexity.ai/

        //numeros
        //:

        const String addIA = ''
            'INSERT INTO access_ia(name, category, entornoEjecucion, imageUrl, webUrl, description, tutorialUrl) VALUES '
            //'("nombre","other", "Online", "urlimg", "urlweb", "/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            // IMAGE

            '("nombre","other", "Online", "urlimg", "urlweb", "/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Magnific AI","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEi7KT_BiLXcIBq7hFS32dKpWgb6B2gAF7XqlaP7z8sRgibskd3g48dMGru5spDmR3edTdntGRR8PHYj8T6kg7t9Exv-PN-UGXoc8xxVgJNauQQyMn-mut149d2AcxEKOcGfZ9UhUIpdS8xPT14rL0P3MIuEBcNwT2YiJwC_bSzAvHTxB85QUjvaWQXk", "https://magnific.ai/", "Es una de las mejores IA para ampliar y mejorar imagen de forma generativa. Esta IA se reimagina la imagen y la corrige ya sea desde deformaciones hasta nitidez. No solo logra un simple aumento de tamaño, sino que también mejora y transforma las imágenes. Puedes guiar el proceso de upscaling con una descripción y varios parámetros./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("AI Logodifussion","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjJqXQxV_RLJSmpCe0crpSYr-odbpCOChiozRH4DqqsERPSlnhuSjAHJfvYrWMrmYNFbNXnYv0IqCS8BqBcLgsXG-EPLiHfIEtcPTaEBK8nzwTFOQJmTiPG2H9FHwGF8HuzlbEFe8s5revEh9-_bdxS_r3XoUovnIKA4_4CcixdcHbLEZSotLK8lwgv", "https://logodiffusion.com/", "Crea logos con IA. Es una plataforma de diseño gráfico  para ayudar a los usuarios a crear logotipos y gráficos de alta calidad en segundos. Puedes escribir una descripción de lo que buscas en un logotipo, y Logo Diffusion generará diseños originales basados en tu prompt. Si ya tienes un logotipo pero quieres transformarlo, puedes describir tu idea de rediseño y Logo Diffusion lo actualizará para ti./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Luma AI Interactive Scenes","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjCL8jEQ_apftMQooAgJzYvx-X1dEsyS53EWW7c6w3q6_EUk-BnFJO6DH6ZGeyzMQaefbJzB54-RujRNS8iuYEVRIkDHWljCimeDaVcTfE2VJ3yfr8sUw5Y-oZlo1h0MWwNWI6r7qT13aZFXswNUeDu3BuY2RuqgPpmwk5hNGkbqE37KSjeignynP2q=w945-h600-p-k-no-nu", "https://lumalabs.ai/interactive-scenes", "Crear y compartir escenas interactivas en 3D de manera sencilla y universal. Con Luma, puedes generar escenas interactivas programáticamente para iOS, Android y la web, aprovechando los avances en IA 3D. La plataforma permite una renderización rápida y eficiente, ideal para integrar en entornos donde la latencia y la velocidad de carga son críticas./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Animagine xl 3.1","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgQo3oL0ukDaLGCGyEzlgvOum8J8PmJWN0byRxSx64OEqiv7T2bjCPAHGUXXtIiLxVhU8HScOXyBOsMRgE8nVPaBwQqB4TLYO1ih__0OAfdIE-retWDRhIMEHTWBSyRDvy25gBECxwXTd9ysetGMVV5s_kt0mDxwq-pAfsCm713sYi0CItYTp3DM2Ci", "https://huggingface.co/spaces/cagliostrolab/animagine-xl-3.1", "Este modelo de texto a imagen de código abierto con temática de anime se ha mejorado para generar imágenes de estilo anime de mayor calidad. Incluye una amplia gama de personajes de series de anime conocidas, un conjunto de datos optimizado y nuevas etiquetas estéticas para una mejor creación de imágenes./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("PixArt Sigma","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhLnjcq3Vncn2WbvZX11uLykQIRaQxAkYC_V6zNi7sVWBKCbIB1qE_IjSuf1li7FKQh_r4xRbSsIE9LZ3lxSmAccynvZLO0r-6mvmKtnpWaMQfLihovXk2wrvIjPYrViasO2Fk64UYZVlAyfv9fpcjKlw0G3EEW6gexkeomhoNoCnBwxHcDiryY1NZu", "https://huggingface.co/spaces/PixArt-alpha/PixArt-Sigma", "Capaz de generar imágenes directamente a una resolución de 4K. Representa un avance significativo en comparación con su predecesor, PixArt-α, ofreciendo imágenes de mayor fidelidad y una mejor alineación con los textos de entrada./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("AI Comic Factory ","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiTQMY_u_SQ-SYRf06DwinOvOQoEIHdJQPFj5NBXWoFe2w-qYgWOAuJUXMb4ayOiL13XG-CmWSHLvFJX5tCCAXvJDi-spQZssz9dRvfNu-VCIf1moNKNeMQXPoJu_aOOGfgI3cS18sqBPlUV-Vz_iUPayCGmbtUSMERI8HWqG2wOy0sDOhMCb3umSHC", "https://huggingface.co/spaces/jbilcke-hf/ai-comic-factory", "¡Diviértete creando tus propios cómics!\n\nPuedes crear tus propios cómics de inteligencia artificial con solo una frase de inicio. Utiliza modelos de lenguaje de gran escala (LLMs) y SDXL (una técnica de procesamiento de imágenes) para generar cómics en diferentes estilos y diseños. Simplemente proporciona una frase o prompt, y el modelo se encargará de dar vida a tus ideas cómicas. Puedes explorar más en el espacio AI Comic Factory o consultar el repositorio oficial en GitHub. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("DocOwl","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjVBlyALZL-ger93vNVSQuHcXoDSsbOQCXULz34SxwJiJMbYc4U6A9muYOv6jvk2c_qYJfeHFvPTKK7AyvLPZ9NUaDEVRYqI4FDorFFYfHJpsi-26trywde6NjNsSnb06okb8D3n6qCTObFBU2uc7iId9h_emzpo83K5pcup7bfGprDDF8GZOrQ4HD8", "https://huggingface.co/spaces/mPLUG/DocOwl", "Es un modelo de aprendizaje estructural unificado para documentos sin OCR, se enfoca en la comprensión visual de documentos. Puede utilizarse en áreas como creación de contenido, edición de documentos, búsqueda de información y más./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Idefics 8b","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjy3eWm634drdEV4dvICuimGEeBy95LOIoV_3DFHthEhcDNhVzPwccwfu2BsSqwB4g3p4ymvDP0y0FUstE1kKaHlyzXxgUevB82ENN_dV3YCJU7qSKHvIwDKOqose8cZNnptiVsVjzLDPee4k7GsGiynyywNjuEfrUDs1A9PZw1FkhN35IEKxsNg8M-", "https://huggingface.co/spaces/HuggingFaceM4/idefics-8b", "Acepta secuencias arbitrarias de imágenes y texto como entrada y produce salidas de texto. Puede responder preguntas sobre imágenes, describir contenido visual, crear historias basadas en múltiples imágenes o simplemente comportarse como un modelo de lenguaje puro sin entradas visuales. Idefics2-8b mejora las capacidades de su predecesor, Idefics1, alrededor de OCR, comprensión de documentos y razonamiento visual. Puede utilizarse para tareas multimodales, como descripción de imágenes, preguntas y respuestas visuales, etc./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("CodeFormer Image IA Online","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhOpT_OmxLhZioODImkOWI8C-TG7FrGZg8Dp79kYHi1U6Q4wetN_iPPymGrKijdaAm2emPRmc_4Ah-R2D218hMLHXQP94qTT8xqEvZAAUpQbu2y0uzUrmN0al0BZgZVtJV-b0T-xa_nljQ99v0EEzlMvSwGpWjPYcQaR3IreBYdU_bgdz3vm4k_uD2d", "https://huggingface.co/spaces/sczhou/CodeFormer", "Restaura y mejora características faciales en imágenes. Su utilidad radica en recuperar detalles sutiles y mejorar la calidad visual de fotos, especialmente útil para fotógrafos, diseñadores y creadores de contenido ./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://www.youtube.com/watch?v=2H6T6H9aFaM"),'
            '("Esrgan", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgLprQouLtiY5zi8YhbdjY_1KBRYMB8Pyl7jqCctXQWW6MCO0O7DA2l8NyG36h-8rCIoXBqJx5QeCYJXPaXXrTPF7qKA9-jmfYODdBtpBPUiEv7hdddx-SuHkrmJhmdgD5N8tTJ_IQt8cDvwrAUmED0E1pCQYRwMQJJIEqRqMvnSVkF95csG6qr90LV", "https://replicate.com/xinntao/esrgan", "Se utiliza para la superresolución de imágenes, es decir, para generar una imagen de alta resolución a partir de una entrada de baja resolución1. Utiliza una red generativa adversaria (GAN) que mejora la calidad de las imágenes mediante una arquitectura basada en SRResNet con bloques residuales en residuales y una combinación de pérdidas de contexto, perceptuales y adversarias. \n\nEstas técnicas permiten que ESRGAN recupere imágenes de alta resolución con detalles más precisos y naturales a partir de imágenes de baja resolución3. Además, ESRGAN ha sido extendido a Real-ESRGAN, que es más práctico para la restauración de imágenes en el mundo real, como la eliminación de artefactos de compresión JPEG. \n\nNo se requiere registro ni inicio de sesión./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("PimEyes","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEg-ckzVyJUaEHpKMYgPhb6mFE7qiuhLkiC3_aRzaMs_WXDgBBBqklew06G_JOrwUKd9OgC5bWZcmjkVcraXGWTWvgb3rnuRdjDhBKwHrIC2XEgJELeyeHfqKdq5BC2iYc6KV6pRXBjnZ04UMD9i130jpGq5-zjgXir81cekfZRcgjs0px8OR_jR_CMl", "https://pimeyes.com/en", "Es un motor de búsqueda en línea que recorre Internet para encontrar imágenes que contengan rostros dados. Utiliza tecnologías de búsqueda por reconocimiento facial para realizar una búsqueda inversa de imágenes. Al subir una foto, puedes descubrir dónde se publican tus imágenes, proteger tu privacidad y reclamar derechos de imagen. Es una herramienta valiosa para fotógrafos, diseñadores y creadores de contenido que desean mejorar la calidad visual de sus fotos desenfocadas/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/3sSa8Rv5Mbo"),'
            '("SwinIr IA","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhjOCUnWaySBho-JE4KOoWROlhSZI8uI_6yP6260p1P5jsw36EB2OgatTUnNk9HOUQev_44Kl2b67azMZxNGcX_OT-A6xaxqzxnhgjOSndTAZVpVBIwpCHjTs0ntHoM0KVD3zTr9job6G4BU98rsSCve6Oxg9iZiSfjwpn49rwatwbLN3sxPt7JF48Z","https://replicate.com/jingyunliang/swinir", "Especializada en la restauración y mejora de imágenes desenfocadas. Su enfoque innovador permite manejar el desenfoque espacialmente variable y de gran tamaño. Al predecir filtros de desenfoque a nivel de píxel, SwinIR transforma imágenes borrosas en imágenes nítidas, lo que resulta especialmente útil para fotógrafos, diseñadores y creadores de contenido. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/XI_taul2wcs"),'
            '("CosXL","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiPo1QbSxej_SpXlRY5oXu6KYztq2DHM8C3FXnoiLQWJ2RWomtUXF-VmD4_IlqyIV6rfrnOK1G9rg63UUsqtn6lbDHK_TpMwIR8sTfExI3kzJVNYFMyvPMrh3lcnI364OlV1Vrcn-MqzSRrsAcwjxGp7vg3DZouaYk8sp1pNpIvfVxRPM4U9zRzbrMm", "https://huggingface.co/spaces/multimodalart/cosxl", "Puedes realizar ediciones en imágenes. El modelo tiene una licencia comunitaria no comercial y es útil para tareas de edición de imágenes. Además, Stable Cascade es otro espacio relacionado creado por multimodalart, que también ofrece aplicaciones interesantes/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("InstantMesh","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjyVjs94Lqj2QPnF3h9jwoVKnf0tF5ZsQQ4oYjue0aCrmKWSnr2VQx60wkaGmYO5l-UOWv1dGAcFbN0eGMLN961SaajIVODO4uOKOKtpGVdXhiDrC1LI71DAEQnU_vS5NPC_KPZy_cXIxAbOJp_pbFLoYSZGP8XLnUe3AIiSP81BgMKOLS_je5VSWme", "https://huggingface.co/spaces/TencentARC/InstantMesh", "Permite generar modelos 3D a partir de imágenes estáticas en tan solo 10 segundos. Utiliza un marco de trabajo de alimentación directa (feed-forward) y ofrece una calidad de generación de vanguardia. InstantMesh es útil en aplicaciones como diseño gráfico, animación y realidad aumentada./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Clarity Upscaler", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgXBZILCT-VExkbq4IMj1yENmA70pcxIXF_lADUIQc_sBbB2NUxic82AzW_P6aWMGc5igepwv6c0lCWXp2KvCK4-iLhKI6zdupiqHp5ZS-GImD-UQx4UUwRzQTuYFUfipg6lMFEELNK8fSpAdKazBFcFBNATxL8tXExZ709x1xgt6ASQiQDQdospDyQ", "https://replicate.com/philz1337x/clarity-upscaler", "Es una herramienta de mejora de imágenes de código abierto, gratuita y alternativa a soluciones comerciales. Ofrece optimizaciones para un procesamiento más rápido, soporte para modelos personalizados mediante safetensors, mejoras específicas para anime y una característica llamada LoRa para una calidad superior. Con una interfaz de usuario intuitiva, permite su implementación tanto en entornos locales como en la nube, facilitando su uso incluso para aquellos no versados en tecnología de IA, y cuenta con una versión premium con funcionalidades adicionales. \n\nSerá necesario iniciar sesion en GitHub para correr esta IA./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Latent-sr", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEh1PQz4y34kwz-LvNcdwz1H4Di2znmQu37cE0nzJGkwDKvdB312vRD2jqUmQTe26BMHauWLhrB7OreV1guqMJwRY9ouGKZkSJrJWCs2CTDJ6cR-_A2XzpJekqRsNVq0IgHQQThsjk95UYaFGkDsfR-CQyn2Kq3RljoREzpJSVd1zLVixDzyeVMqBJc_", "https://replicate.com/nightmareai/latent-sr", "Se especializa en la superresolución de imágenes utilizando el modelo de difusión latente1. Es una herramienta que permite redimensionar imágenes a una resolución mayor sin perder la calidad original, manteniendo la composición y armonía de los detalles y texturas2. Una de las ventajas significativas de Latent-SR es su capacidad para manejar texturas y detalles finos en imágenes generadas, aunque puede no ser tan efectiva con imágenes del mundo real.\n\nTendrás que iniciar sesion para correr esta IA./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("InstantStyle","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEj-PtRgSLHP28S8_IY-UcQ3LMWgxjPP1-76ZdSWWwqaVHrnyhoABWMysaFs8aL0ftWb6EzIKFLZuWCGFGU3SKjNZcPzHwo3SesaIV9GKGJylwpxjvk7fnDpsygDuUSuDEIalbcw6qxHAJUNNjpEe9W06l8ukWBt91J3izmJSFmhe6VWllXB67mXxLuK", "https://huggingface.co/spaces/InstantX/InstantStyle", "Generación de imágenes a partir de texto con un enfoque en preservar el estilo. El objetivo principal de InstantStyle es lograr una efectiva separación del estilo y el contenido a partir de imágenes de referencia. Esto se logra mediante dos estrategias clave. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Face to All","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEj-VA1W8ycPZ3g3ACkCC02BlXKON26Rzy0jPtgXT_w8LnskpxEgR3Phhnu63xKRMn_TM_lu5FQNtyD57lmTj-uoHEg_dSQt2tjf6fJuHdhks4gKp081_8LxipZf0aX2rCBnemykHJD2ZWLQJIhP9q1yQvHqrtyMD2JYwKTMRczATCnczCbCtINQ_Rb_", "https://huggingface.co/spaces/multimodalart/face-to-all", "Convierte tus fotos a cartoon, personajes de video juegos, o animaciones en 3D./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("BigColor IA","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgnkzUQCHuBFNO3rR75Gyyt81FvcRNQs-ca1AAWUWajvmNuwPX6xnxEQltI5LkxmrD6QYS1VK4PVN8r2l4GRfSS7KyQHrdT8OlhogSffikOyK5WfHO9HU4vxM93JhFN7gVWnHK2NngSJMnug3s4Q2Fqmo4nJ0YWP4hmATIBWXrq1la-Z7Uxg9ROnz8Q", "https://replicate.com/cjwbw/bigcolor", "Aborda el desafío de la restauración y mejora de imágenes desenfocadas. Su enfoque innovador permite manejar el desenfoque espacialmente variable y de gran tamaño. BigColor predice filtros de desenfoque a nivel de píxel, que se aplican a las características desenfocadas de una imagen de entrada para generar características nítidas. Es especialmente útil para fotógrafos, diseñadores y creadores de contenido que desean mejorar la calidad visual de sus imágenes./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://www.youtube.com/watch?v=TEJIzVrO9xE"),'
            '("Diffbir", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjF2Ht_PIFgjp0MsW1EDZU2G6pK6-jgwkAjFjx-5bnZQZfh2UG1s91Db6NsZ5-RaLeMmIoEFwL1VwZ264foC2itoiwCNXiFGOnV01ss9vkllp3MOIHw2v7vuf7f8w7Ixxefz5CLJg8tqz6HC0eXB8i050AQiuEpPWaNx5g0InSn99CHRHEtFbIZ_d0O", "https://replicate.com/zsxkib/diffbir", "Esta IA se centra en la restauración ciega de imágenes utilizando modelos de difusión generativos preentrenados. Es un marco que adopta un enfoque de dos etapas1. En la primera etapa, se entrena previamente un módulo de restauración a través de degradaciones diversificadas para mejorar la capacidad de generalización en escenarios del mundo real. La segunda etapa aprovecha la capacidad generativa de los modelos de difusión latentes para lograr una restauración de imágenes realista. \n\nSerá necesario iniciar sesión para usarla./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("DALL•E 3 XL v2","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgFD8CUQpcjM-EQ1rtg5yM0EKXokSmi5gqm5CggPSZ3A6pUr9okl0oRySWxdVVDeQymssYqqXxDdiE-0ceI4HSzbkoPTaomIpo_dXEjdmJf0CqPLgN3BWGPdPyEktCaxvu2gvDMDjAzFo8oXzI1QHw6JOD-w7oYbB8EvpqpfVCRLzs4tY33dQPUyC6n", "https://huggingface.co/spaces/ehristoforu/dalle-3-xl-lora-v2", "Generación de imágenes a partir de texto. Puede crear imágenes vívidas e imaginativas basadas en indicaciones textuales./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("IDM-VTON","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiIxX-iaRTnKkodW3oouXaMSOAwv-f9ypU7H-oGBfkyfxuc6D8byDDykqP7Qf0CehvhjmpEzZBjoGU07Kj_OjmUgBb2e1ZvbHu1x2Ds63n-tkX8NdUsde5zfEDV2NvLN-A-G9qy_2yj_YriNZ4y4OAgEg5v8PeEIyBYAmFNKG-UExu4rQKDDDcrvxn_", "https://huggingface.co/spaces/yisol/IDM-VTON", "Permite a los usuarios ver cómo les quedaría una prenda específica antes de comprarla. Prueba ropa virtual en situaciones del mundo real. IDM-VTON es un modelo diseñado para el “virtual try-on” (prueba virtual de ropa). /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Pfpmaker","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEi3BB7mjf3VVOfa_coj9PBEVUJ2pmIqodvdn-VA9MWhbQYjG1nQAkIs5STWqox6RYlRh2TGJkR65flZJKQXMgB05y3m5zKMhcYh8GW-biS8iSCx7oMcGd38-1NGB1WoVafPbD6s-y1y0n9gndDrCCOK2j2KNenqs8PqD2fvsAAhYlwMx008--qPg5Ge", "https://pfpmaker.com/", "Ofrece un generador gratuito de imágenes de perfil. Puedes subir tus fotos y la IA generará cientos de imágenes de perfil profesionales para mostrar tu mejor versión en línea. Ofrece estilos de retratos de negocios para LinkedIn, CVs y currículums, o estilos creativos para Instagram y mensajería. Además, puedes personalizar cada detalle de tu imagen de perfil con una amplia selección de herramientas, experimentando con IA, filtros, fondos y plantillas para encontrar tu aspecto ideal. No se menciona explícitamente si es necesario registrarse para usar estas herramientas./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("DeepImage","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEg-2bAlC2vmKndJ4ADbtzZYv_tpY402ykizWiJXM-8AMfzGQGdLsPVUdM6rGLSDwnq3IrFVjIel3QWQdcgZVrv9vCyAXgmxXIkXyyDBbCM3g-_qpjUxprMCu_dZiuK8jJ_OxKxeS6njBLQ1THjccWOCtOpSM2ZVQI8Atbv9wJxRa_JrcuisjnRA9kdv", "https://deep-image.ai/", "Ofrece una serie de herramientas para mejorar y ampliar imágenes. Puedes aumentar la resolución de las imágenes hasta 300 megapíxeles, eliminar artefactos, corregir colores y luz, eliminar el fondo y más. Además, ofrece la posibilidad de generar fondos para fotos de productos para comercio electrónico, marketing y propósitos promocionales. Deep-image.ai utiliza algoritmos de aprendizaje profundo para procesar, analizar y entender las imágenes/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("BigJpg","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhpVBNlLHX5eVhfiyXyf7J9Behu1Qf4QtbveqL6czmOsiRVyxbhbt7KAC4rVbSbVlMr0fC-tHI8Nog9xuyfFoqaXxaH2wnxlb3jtmo5xIhUqh7O9vUEeeYCUvbIAljdHfLLh7OPOgJnbdSYg_CmS1Eqete9bo4RVRvrYrtjHkjensoHfhWIQUHhORj-", "https://bigjpg.com/", "Ofrece una herramienta para ampliar imágenes sin pérdida de calidad. Utiliza las últimas redes neuronales convolucionales profundas para reducir de forma inteligente el ruido y la dentadura en las imágenes, permitiendo que las imágenes se amplíen sin perder calidad. Actualmente, los usuarios gratuitos pueden ampliar imágenes hasta 3000x3000px, 5M; los usuarios de pago pueden ampliar imágenes hasta 50M1. Las imágenes subidas y ampliadas se borrarán automáticamente después de 5 días./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Ultimate sd upscale", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhlax9-1HArVqo91ulCmmpB1_L-8hovThWXFogSRwpzUjHy3Kxf58Z7nU2vMdfK97m1eyiGu_eMagBQuPrca4mZaVdau1ohTcEKwBGoEA0qCbp4TyIhu2fW2EGm6qcz2bchFiUPNI0xNKqY7zu-PQzhVUhi1K8-0Ug2xrjAH-HNuZYQVNTgiyq8Tzcx", "https://replicate.com/fewjative/ultimate-sd-upscale", "La IA Ultimate SD Upscale con ControlNet Tile es una implementación que utiliza deliberate_v2 como el modelo base SD 1.5. Está diseñada para realizar mejoras de escala en imágenes./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Supir", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgbXvkeq7B0PFZ05OPwVCxltMZPq9WlCFW4briiP-1uag90mBAbQuFsiByUBniNteJnyi6VxFxtsx4lH2k3yadu5OML7ORKxDGVPwF8MeMApJHs5yPoO6_8hvR6k-99WRSs6HDz9SyUtIJKlMeXENRdAjeNnxY-Mkhzzl5q3n95MiPD1SVVvGOjShnt", "https://replicate.com/cjwbw/supir", "Es un modelo avanzado de restauración de imágenes que combina la tecnología de inteligencia artificial con la creatividad para revitalizar cada imagen, dándole una nueva vida. Utiliza un modelo de restauración general de alta fidelidad basado en un gran modelo generativo de difusión. \n\n No es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Pasd Magnify", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEg4mWdGdiXT1USYKpMSa7AO8XAU6iMxp2GEvxFyjkfYLROExB0SY2PqmyKGcRVRanwt5ire20S317vPB61GW4vBZsBvZPftfLVRaZWwKQ2syb17V4CBKlc6V_Wy_lR4hAz3qxcYO3KtYgOlhr8FTgmPsiJn47DMRKmieULwJpIXlT0sMuzjYVd3xK0g", "https://replicate.com/lucataco/pasd-magnify", "Es una implementación que utiliza la Difusión Estable Pixel-Consciente (Pixel-Aware Stable Diffusion) para la superresolución de imágenes realista y la estilización personalizada1. Este modelo se centra en magnificar los detalles del sujeto y mejorar la calidad de la imagen. \n\nSe ejecuta y permite a los usuarios interactuar con el modelo a través de una interfaz de usuario, donde pueden ingresar un texto descriptivo y ajustar configuraciones avanzadas para guiar el proceso de mejora de la imagen. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Adobe Firefly","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgmN7v7BZrs3uBQiu_aD365hCnt4ZsVBnr_7VfKQEGnbDYv6XKSiEsViBcqwo79ZWToFSao_s8nuYqGq8GwfCM1mSJk9ouUe3-udvZ-W2IBT9q6_eOzbpQyJG0vrZKf-Ev-02wqD4Jfe5TAyWDmvlhlnsfRrMl1_VA55TevJzyhZksjD_X4joiIccX4", "https://firefly.adobe.com/", "Es una aplicación web independiente de IA generativa que permite crear imágenes, efectos de texto y paletas de colores a partir de instrucciones sencillas de texto. Se utiliza para generar contenido nuevo a partir de imágenes de referencia y explorar posibilidades creativas con mayor rapidez/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Upscayl","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhNiOHSPzjGOe5Dz3Gm2LR7VaQdR5Knsvpite8M7nnSwyFo9GqD5hCMo7HuRyDEDlwqPGjeG9g9ALNpkgl1H1_P_fjD42XBs0jBRVx9cNLHsgPxDgNceXpXXwUBDj4ZDEJzhcyW4gFV5ZB4sAjsHdqQqvZ0LAj0bvSzyciExvptXMaNxoeFK0e9G5IV", "https://www.upscayl.org/#cloud", "Es una herramienta gratuita de mejora de imágenes mediante IA. Utiliza algoritmos de aprendizaje profundo para aumentar la resolución de imágenes de baja calidad y mejorar su nitidez/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("IllusionDiffusion IA","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgBT2-D8Q-2p2B1w5mZjwTwMp5OtJLKb4g-cML9GAYBHZ1QXP5HIGnYenOrrRiJonueoFrKknHxdeYnbxejAA5Kf7v4G8L7j-pk4Y7MD5wq4RxlE_KIFTapi_DSWHfBqSUUtgGHHphUB78ph4TaSRl7-VKqpYY3eQbRgangJd6AaduT1kj-AvqLyFLU", "https://huggingface.co/spaces/AP123/IllusionDiffusion", "Permite a los usuarios explorar una colección impresionante de aplicaciones de ML desarrolladas por la comunidad. En particular, IllusionDiffusion se destaca al transformar imágenes en ilusiones ópticas, brindando una nueva vida a las obras digitales y ofreciendo una experiencia creativa única./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/ksrRmDU6KVc"),'
            '("Ultimate-portrait-upscale", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgEPSYTb4fgwAZ27NK9hCl3eCfDC0FNJ2aGJvL16sKCFHIq2s9fMGo7Zvca8tOgbUgIZTioKX-h-GBeZKty7O5KKykaGZR1K5PKMmAeRiadqNsFRQdFz0zIYbSPj6TH1qfsv1_hqzMFyWW78Jpgpm17QuTBX_NL4YRfX3B4fdcRFW0xLPPtRZcBBX-X", "https://replicate.com/juergengunz/ultimate-portrait-upscale", "Es una herramienta avanzada para la mejora de retratos y fotografías, que utiliza inteligencia artificial para escalar imágenes a una resolución más alta manteniendo la calidad y los detalles. Es ideal para fotógrafos y aficionados que buscan mejorar la claridad y los detalles de sus fotos, especialmente en retratos, hasta una resolución de 4K. \n\nNecesitarás iniciar sesion con GitHub para poder usar el modelo./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Seesr", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiTAL_1uvlFOrNRqfJ3tcOIdDmz0kUx2nxrLknHKTrc-DTwBnPwwPfLmHbHdKVna0-Zalw8cvzmT2OQSN8bu56lgRwoX3stInxHhshV6bS55TsDcLdkR9ezImaK3DfdH39ua_9ssibLaa7Oo6YwHYHycrB-RM_dofudf89T87ZmLZGU6H8TbPKo0Iqh", "https://replicate.com/cswry/seesr", "Es un modelo de superresolución de imágenes del mundo real que es consciente de la semántica, lo que significa que tiene en cuenta el contenido y el contexto de las imágenes para mejorar su resolución. \n\nFue presentado en CVPR 2024 y es notable por su capacidad para obtener imágenes de alta calidad con solo 2 pasos utilizando el modo turbo.  \n\nCuenta con un demo de Gradio, lo que facilita su uso y acceso.  \n\nEste modelo es importante porque permite mejorar la resolución de imágenes de baja calidad manteniendo la integridad semántica, lo que es crucial para aplicaciones como la medicina, la seguridad y el entretenimiento. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Demofusion-enhance", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEi0std_c8OAVT66nildUIXJcP-t5PiJYNN-rnF7ErHI770imv9GdkaQAb3LjzWY03NdyD66wPSOuUBR4UeAjvGWDhNPI52_hddF4bgBPspYMqspTzoPCJ96i99KGX5XagMfzQPE4t4fgZdE_FX6RgA4xqwwUfQn2fFIcmJkV13R7EHv8X498h4tT3Da", "https://replicate.com/lucataco/demofusion-enhance", "Imagina que tienes una foto pequeña y quieres hacerla más grande para ver todos los detalles sin que se vea borrosa. DemoFusion-Enhance es como una lupa mágica para las imágenes digitales. Primero, tomas una imagen básica que creaste en tu computadora o encontraste en internet. Luego, con la ayuda de DemoFusion-Enhance, puedes hacer que esa imagen sea mucho más grande y clara, ¡como si estuvieras usando una lupa súper poderosa! Lo mejor de todo es que no necesitas una computadora súper cara para hacerlo; una computadora de juegos normal puede hacer el trabajo. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Stable-diffusion-x4-upscaler", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhw_wp7OPhUJdXYsrnnkzhkkWfTv9AKMJHYGy96xnakKO1Bl1-VWw9DIbCiIkO3nTTMfUXHVPLKK_96W7fQVCXSktwoDdyCttk9Vl2148Fm4QF0FqZMLCKd8jSQMtN4xPxwxZV0J90xh3r944Nk1dhZKZi_8RC98z4r8DEyzlTHrjSQi19QxpackLts", "https://replicate.com/lucataco/stable-diffusion-x4-upscaler", "Este modelo ha sido entrenado para trabajar con imágenes de más de 2048x2048 píxeles y se especializa en el escalado de textos guiados. Además de la entrada textual, el modelo puede recibir un nivel de ruido como parámetro, lo que permite agregar ruido a la entrada de baja resolución de acuerdo con un horario de difusión predefinido. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Real-Esrgan", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgNK71n86eqbfCOQYdqgJeEIuc4EGEGY4zZ-C4_RUVr0TwjbXILcQzlVob1IA2GQ2y02C4ePooVVkbqnFphIELSETS-qv8hsGgD_BdptEv349_wQ8sHgZIhnh4MoHfgeeUyO3U3RywjVcDZO7z1Vd9hKWrIw8NGoEsbnab6O4LcAQxFPJSZSwJBRNQH", "https://replicate.com/cjwbw/real-esrgan", "Es una IA pionera en el mejoramiento de calidad de imagen. Es la implementación en PyTorch de un modelo Real-ESRGAN entrenado en un conjunto de datos personalizado. Este modelo muestra mejores resultados en rostros en comparación con la versión original. También es más fácil integrar este modelo en tus proyectos.\n\n No es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Rudalle-Sr", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhoqgBJb2kDRTt3mjZgJHXZ8W8jiw6sL1iTd03osDJH4OPLmUVNL6-7XLdQ97SJRhavUx68Tj1UbqOJqvfaHCjaYd52gIuGSAqr1FWgkjcP5_0Jwp686st6U5oEbGEkHrG0j_hU1MG2pPGhgQc3VDY3naNn8LXAJFffoc8V5TENuznkR6T3Cw_fLHCq", "https://replicate.com/cjwbw/rudalle-sr", "Este es el modelo de superresolución Real-ESRGAN de ruDALL-E. Este modelo funciona con hardware Nvidia T4 GPU. Las predicciones suelen completarse en 77 segundos. El tiempo de predicción para este modelo varía significativamente según las entradas.  \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Magic Image Refiner", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiEqGSk9dsfTmeZsViQo3a-nIAkbk2gS7WiKlZKTnJJsBGWksgEOMbMK6TrFa5ah3q7273eBN5EJV434Wy-n0q0_jQH-xFM61GraKnLFkwDuV_a8JPg6T1wvGurKUxXOBNZkHxm7-_jSz393WKnWElwHOmM87YU4SagY0YysJ-PJVuLbeGBRoAuiv-u", "https://replicate.com/batouresearch/magic-image-refiner", "Con esta IA puedes rehacer la calidad de una imagen mediante un escrito o un prompt. Debes subir tu imagen y escribir el contexto detallado. \n\nEs una mejor alternativa a los refinadores SDXL, proporcionando mucha calidad y detalle. También se puede utilizar para retoques o aumentar la escala. Este modelo funciona con hardware Nvidia A40 (Grande) GPU. Las predicciones suelen completarse en 54 segundos. El tiempo de predicción para este modelo varía significativamente según las entradas. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("High Resolution Controlnet Tile", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjS9oy0nQk0E5XqHJ-vj7Dp8EbNF71glTZCZu1CsC4lecwBHcsguHlGJ9HDkSGX1XckTcxXPt9ha9lPggfmxDzxb-WYSTwx6_ZaTpEjsaw2YUE9E5XuyPWAfX020eQRVyAxt1gM-fbN6zGAx45vqIi4nKmySMq1TVZFcC7nlQkkHmH4mEeUql52coGC", "https://replicate.com/batouresearch/high-resolution-controlnet-tile", "Permite generar imágenes de alta resolución, incluso en GPUs más antiguas con al menos 4GB de VRAM. Se utiliza en combinación con Stable Diffusion y extensiones de escalado inteligentes para renderizar imágenes en resoluciones como 8K. La guía de ControlNet proporciona instrucciones sobre cómo usar ControlNet, incluyendo la instalación de extensiones necesarias, el proceso de escalado de imágenes y consejos para obtener mejores resultados.\n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Swin2sr", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgFPhvvd3tz8tzC5PeO2iz_jYaZtdWhNaresSQ7O6T3NE0-CgRzhEP7kiNuBr0QYhqlilauZZq0h7vxSeHu5do6wr4PQx7vmWaBsAgtwExvni_WbD3O5FShTlGuNCoAnQD4ZnfLYd8sfWsXks4836I5vM_6jFasloLHc61lCUOnDYIZ6BDSemzG7ylC", "https://replicate.com/mv-lab/swin2sr", "Es una IA perfecta para eliminar ruido y suavizar texturas. Este modelo funciona con hardware Nvidia T4 GPU. Las predicciones se completan típicamente en 19 segundos. El tiempo de predicción para este modelo varía significativamente basado en las entradas. \n\nEs facil de usar y te ayuda con el reescalado de la imagen. No es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("ClipDrop Image Uncrop IA","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgabiP35k863OlOZ_iVLVlAmDLNRLIHd_TEBLeqOilcfnTEERKlQuvdyeN8uIN5bIfagDRISCV2jsV16ulWdgxGnoyUnR1memgY7C-brXjD-6d502hs2SmKYLrApS0R_U1yxf4jVPX7gbqccQseLWw3a2zOFMDGQ-ksHGA1bdSGvAkU1fY7XGos-ENB", "https://clipdrop.co/uncrop", "Es una herramienta optimizada para editar la relación de aspecto de imágenes. Está basada en un modelo fundamental creado por Stability AI. Los usuarios pueden cargar imágenes y seleccionar una nueva relación de aspecto. La herramienta generará la imagen con la nueva proporción, permitiéndote ajustar las dimensiones y expandir el lienzo visual. Si tienes una imagen recortada o imperfecta, Uncrop utiliza tecnología de outpainting para reconstruir y extender la imagen, como si fuera mágico./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/V9Ucyq8c00Y"),'
            '("DragGan-Inversion IA","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiHk0O2I7W8XbY_gxulrxn8sXgz-Q2N_rxtK3iFT0NW_6KeufQUoO4KkEbDw-T2Luh5zrSZFZ-OFt6SVtLS1R_PnmolfdQrklD3w0DS-yq7lAVjZNKNF1hW_6D1gJQRlvnUD7-bX4Av-y-bKMZ6LPGg4j2okR_YGCdfEiafZUrJLfnSwZ_Yx_C2f_9P=w945-h600-p-k-no-nu", "https://huggingface.co/spaces/Amrrs/DragGan-Inversion", "Te  permite manipular imágenes generadas por redes generativas antagónicas (GAN). Al aplicar la inversión GAN a una imagen real y mapearla de nuevo al espacio latente de StyleGAN, DragGan te empodera con capacidades avanzadas de manipulación de imágenes. Puedes ajustar la pose, el cabello, la forma y la expresión de las imágenes, lo que resulta especialmente útil para fotógrafos, diseñadores y creadores de contenido. Además, su enfoque en la interactividad y la precisión lo convierte en una herramienta valiosa para explorar y experimentar con tus imágenes./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://www.youtube.com/watch?v=zTqtZl8ALJ8"),'
            '("ifan-defocus-deblur IA","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhbulHI9XYP6mD8Xs_SJzcmVNLlM2hhm1bnunK4Pifyx_KgbDUcrBc0-wfLNokGmYtiYazN4kB8s6-1_vYSrFGQ8HG3lg-J6oxYWsxVFISg0L2RLyXb8lq1y7Z-Kx74N_Au9B8Igc6MiuBwc49FRVcabUPjM_Nkk5wCKS80XpEn2mC7MFv3Fr4OwwpK", "https://replicate.com/codeslake/ifan-defocus-deblur", "Aborda el desafío de la restauración y mejora de imágenes desenfocadas. Su enfoque innovador permite manejar el desenfoque espacialmente variable y de gran tamaño. IFAN predice filtros de desenfoque a nivel de píxel, que se aplican a las características desenfocadas de una imagen de entrada para generar características nítidas. Es especialmente útil para fotógrafos, diseñadores y creadores de contenido que desean mejorar la calidad visual de sus imágenes./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/Ed_VNV-X3-E"),'
            '("NafNet IA","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhSkIN6UZNOdB9MEaAPyEqvsc0UDn4FwiKRq5kiGyIEVHgox2jIV22eLlX4KBrquZpMUYteD1uFo8yD9r9vYTGqDuTWZkQ5koKluZq653cbSj-TRukRnrllSLcjlMYTFDzPLbwcHDemtru6pnqfnRR-HEy8OnjRlN4XAGuBBiRb4pqSyskVSOvYRdlX", "https://replicate.com/megvii-research/nafnet", "Aborda el desafío de la restauración y mejora de imágenes desenfocadas. Su enfoque innovador permite manejar el desenfoque espacialmente variable y de gran tamaño. NAFNet predice filtros de desenfoque a nivel de píxel, que se aplican a las características desenfocadas de una imagen de entrada para generar características nítidas. Es especialmente útil para fotógrafos, diseñadores y creadores de contenido que desean mejorar la calidad visual de sus imágenes./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/ijFPxRUQKMQ"),'
            '("Colab CodeFormer Image IA","image", "Online Colab", "https://blogger.googleusercontent.com/img/a/AVvXsEgwHQ4av4O3IYI_Pn-rY6vDr-LFEeejXb9TIlIk6RUDJXDcVZ8B26tUdxWlwQDT6UzYO3f_7Q4umZN6I-bki69NiqNTbe5lKNlkx2kYZ3ve8mfWafEn-F0ojeb-bjdLmKzvzb9X5b9LnZ1VZkoA489wPjl6mjOY2zH_7FlQoIPLTnYJXto8uIwbvRuk", "https://colab.research.google.com/drive/1qhkSMVMDQa_IgnBOAuQzEkJCNke_6u5v?usp=drive_link", "Para colab. Especializada en la restauración y mejora de imágenes desenfocadas, también puede utilizarse desde Google Colab. El equipo de TICnoticos ha desarrollado el código necesario para implementar esta funcionalidad en Colab, lo que facilita su acceso y uso para la comunidad. Si deseas mejorar la calidad visual de tus fotos desenfocadas, CodeFormer en Google Colab es una excelente opción para explorar y experimentar con esta tecnología ./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/GDnfPeFkC6U"),'
            '("Colab REAL-ESRGAN","image", "Online Colab", "https://blogger.googleusercontent.com/img/a/AVvXsEiPdMfQFsklTjJoQHJlPeg7tiR64Hkb6m100ZC2YDAFI1pO7RM5hH49uTXpEzClLF0q7YrBRcZAYNUvHN_myBwlm0b5resk8AgNKnwUyBF7AvrLkJbbvMHJdHxVcO8HY0JloU1QI2ugBIqMoOJZA9dTV7raJ1q10fEyht25ZAy0S5maRzVXtzZSRBuh=w945-h600-p-k-no-nu", "https://colab.research.google.com/drive/1vEFwY3bGRvMycuXKU86Tuqytw2HZytTg?usp=sharing", "Esta IA es genial para restaurar calidad de fotografias tipo retrato, paisajes, rostros, texturas e incluso dibujos y caricaturas en 2D y 3D./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Krea AI","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhKVj3m94Z9WimjGrbmW8tRsZM1qqaLPu8tkjClWYJ2VkhI7ateLvUAXTgpOtxO_CLzQL0CL2zRZPKHTye9ZK_HPAhEEecy2UWUD-UA1ucR_o7l5t400hNcgGUU-i_UJXvufX4fa8sj2Y_95XmQ3snSBQBhQ7GgCIRgpE0uh4HCqpC-pdRuFeZEHQ7w=w945-h600-p-k-no-nu","https://www.krea.ai/apps/image/enhancer", "permite generar imágenes en tiempo real. A través de esta plataforma, puedes experimentar con la creación de imágenes utilizando técnicas de IA generativa./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("HcFlow-Sr", "image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEha9LYrH5r_nOJibejtx1RtQxaDV6IQIStFCzXwaZoHFAOOYG-l47_3obZ4ym8vtmYMlBaY98ke1CXnT8272-GCt_RKLXzQYRQAafCgtx3XyPj5__VAcqRK0Z9VKlAgPputJCfclGjG3_sZUOa7H8E6gWLJnINSO_Kw-f_le2hifqetziedP-d1C0rb", "https://replicate.com/jingyunliang/hcflow-sr", "Esta IA es impresionante. Restaura cualquier imagen con rostros borrosos o desenfocados. \n\nSe trata de un marco unificado para la superresolución de imágenes y el reescalado de imágenes, conocido como Hierarchical Conditional Flow. Este modelo utiliza flujos condicionales jerárquicos para aprender un mapeo biyectivo entre pares de imágenes de alta resolución (HR) y baja resolución (LR), modelando simultáneamente la distribución de la imagen LR y el componente de alta frecuencia restante.\n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("HotPot","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEizkgChUMk-F-rdpMaXypEps5oaWb-swIENWWi4UukXUcIXukH4IpyE_HUis9GFEWgLO_8F18wRLwyeBlhCf8w8lE-FszBUwJ8fqtShr9u_EghNtt1cGaUuPttY4ofc0FsG5ePBFTaSuzmsHqZpnvdm4k3IiCwXjIpJa_1KlM4Qn9yH6xvQLzuYouSa", "https://hotpot.ai/", "Generador de imágenes, edición de fotos con IA, y creación de gráficos para redes sociales, marketing. Puedes visualizar ideas con el generador de imágenes, reimaginar tu apariencia con retratos generados por IA, y automatizar tareas con herramientas de edición de fotos./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("MyHeritage","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEirl8zrcvqrazwmrTAQ6gHTmofAQgCPjTZowrCkxXPmvEHZjZ3iGUfXwgzT8x1dirJyU0SVS22kEHxf02RrVAPMXFmI8LLOVFOy7b9aNqeKqUxFSIZNs0kd63FfI5HgbwggZ3ZWjwbgFTRVT89Gl_6_XD5tN4hZ1m3zLZ8VuPGCZtUviWa6UoSSW8J5", "https://www.myheritage.es/ai-time-machine", "Utiliza la Inteligencia Artificial (IA) para ofrecer características innovadoras en el campo de la genealogía y la historia familiar. Una de sus funciones destacadas es la “AI Time Machine”, que crea avatares de IA de una persona tal como pudo haber sido en diferentes períodos de la historia. Puedes subir tus fotos y verte a ti mismo como un faraón egipcio, un caballero medieval, un astronauta y más. Además, MyHeritage ofrece “AI Record Finder” y “AI Biographer”, que transforman la genealogía utilizando la IA para buscar registros históricos y generar biografías de IA. Estas herramientas pueden ser útiles para explorar y entender mejor tu historia familiar./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Remini","image", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhbYiFfE7bXTmTY8CzvXpBnvsPjVJRcDGQx4yleyb1w6Ud_dMaX8yec8-FwJkO_-3vZbyAthrvwDiEz7yax4q3fMivCJT4nXpyJ2FPGH318LUpdCZ6Y60EfkCR1CjsVPjLZgifxGeW7Td4l5t-ObujTmExRRF_FwtxFsm1Cc380JS5yKN1GDfY7B_lW=w945-h600-p-k-no-nu","https://app.remini.ai/", "Esta IA mejora fotos y videos. Utiliza técnicas avanzadas para eliminar el desenfoque, restaurar fotos antiguas, reducir el ruido, mejorar rostros, corregir colores y ampliar imágenes. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/uk4Vo8FYPFQ"),'

//video
            '("Colab FPS RIFE 2024","video", "Online Colab", "https://blogger.googleusercontent.com/img/a/AVvXsEjdueYU_UivlTCndEyVoTbnDQ4usSuZdS1UjXt1-ihhVHxnisDh04aM4eymhskjs2eZ0YbMnuSi-jT07TbExXq7y_kWSt0j6u8gv1TawAT45IKY8RWH_h3W8X33XAZbTXE-wI9-IVg8GYSoVQTtcWhEWVxsFmXOQv-Be4gNVrvp2OVMgw40NkwswucE", "https://colab.research.google.com/drive/1r6ff8V5lQG38GabaEkHyTbsaVsqFu_54?usp=sharing#scrollTo=fmF42gwvs2zH", "Aumenta los fps de tus videos desde Google Colab usando la IA de rife, actualizada y sin errores. Sigue paso a paso el tutorial de YouTube para evitar complicaciones./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/h8JlQ2AmuZ8"),'
            '("Synthesia","video", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiFU4ODpzVDPOrxs-rAEI6m3uRNDjy65CS2jyNKI3gcfcvY6j7YLIRLRwCO_edNlDAjhOvp8dCWsui3ofTUZaOK9VBD7T_b5EkWinzAknD--_n4JASomwODBRBA-54zxvlkBtTI3mKdIm9bgBHUVsxDXdU-pGsCZHC0j1u5jmbj6FlWnl2Ugml3RRxR", "https://www.synthesia.io/free-ai-video-demo", "Esta herramienta te permite crear vídeos generados por IA en 120 idiomas diferentes. Es útil para producir contenido audiovisual de manera rápida y sencilla./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Colab GFP-GAN 1","video", "Online Colab", "https://blogger.googleusercontent.com/img/a/AVvXsEjiOtuJO417ZjXifmI3BqEKoxlxLe0BTKyGVUxwTwseQqFvtQZdl54Ig5NQfhBHmE_mAajp2U1zS5nvOhlo1C3oG4DV2TuJ7ym3V5bDK0HCvwsIXcs98fPk_KqkKUIVPUNFmFEngvppEtAbgfEKD2g6HlyY4jwfhA5MPbmtQCVHmwEkXXs2ArPwZj2t", "https://colab.research.google.com/drive/1Z6RINOM-wTmXcWuHatgPpJ5nVg39bZkr?usp=sharing", "Es un proyecto que se puede usar desde Google Colab, que se enfoca en restaurar rostros en el mundo real. Utiliza una red generativa adversarial (GAN) previamente entrenada (como StyleGAN2) para llevar a cabo la restauración facial sin necesidad de información específica sobre la imagen original. \n\nTicnoticos ha desarrollado un cuaderno en Colab que permite a cualquier persona probar GFPGAN, una inteligencia artificial para restaurar rostros en imágenes y videos. Este cuaderno es de acceso gratuito y ofrece una forma sencilla de experimentar con esta tecnología de mejora facial./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/1dqn2_qCR9Y"),'
            '("PixVerse","video", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhSVD8teWxm5tH5-sOmpwf9zyE72aSQGohNzgXrhcHZG-3UH5hTwzR2euaJMHg3zXp7kPbxB3WYyiL3J0pk7I22htp_9EDsJFlo6dBsm7O6Off4swxWBI7NqfT6Y-0FyV5y3g2qVOdiUA6jcd37tEkioX632y9Yu7ttkdtv2c_P3dKD--EvrUBA5pVH", "https://app.pixverse.ai/creative/list", "Creación de videos impulsada por inteligencia artificial. Permite generar impresionantes videos a partir de indicaciones de texto. Actualmente, la herramienta utiliza su propia interfaz web. Después de registrarte en la plataforma, puedes ir a la sección de generación y usar la opción de crear para generar tus clips. Al crear tu indicación de video, también puedes seleccionar el estilo del video entre realista y anime, así como otros ajustes como la relación de aspecto y la indicación negativa (si es necesario)./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Colab GFP-GAN 2","video", "Online Colab", "https://blogger.googleusercontent.com/img/a/AVvXsEjb2pHYToI-ZV1covB_Jvb0jsG1StOeiOSc5845nHCzgXvCgRD4l9v4ykj-8prT4g1Zj3GXngV5-r7mmTxow2tR6JhSNgDUZcE1emT1A_pBj4kceyN3z2OMaD5HIxuP-9EtrJ2k7Kqee_qOqaCo1E4g0EYabWhJjZF4rkJt09nGkjrMvdr2_oUoyVvB", "https://colab.research.google.com/drive/1T9ia0rP3lWy2m4tTlHHYLCULvLqZC9If?usp=sharing", "Funciona mediante proyecto en Colab online. Utiliza una red generativa adversarial (GAN), como StyleGAN2, para llevar a cabo la restauración facial sin necesidad de información específica sobre la imagen original. GFPGAN es una herramienta poderosa para mejorar la calidad de las imágenes faciales en videos y fotografías./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/AWR50OalMB0"),'
            '("Colab CodeFormer","video", "Online Colab", "https://blogger.googleusercontent.com/img/a/AVvXsEgaJz89rhwDv_mwnmS85ukwaQZAEggu5oca_RgHPnJA1pxMvvqJkTfdVN2C4jxluolvneA3Rt0QdbpiLsgPi4hovrrapwvDdfDVlU2t0cjk_PWtJ-UkoKyC43scvmgVJnXxSxRuoZJglIcwbwHD-g-D8qQXf2G1g9YFY87S9yYjHbc-J48hcrgn-l3b", "https://colab.research.google.com/drive/1yAMhqxgnp5PLkIuJdYXlYFo90rEAcge0?usp=sharing", "Es un algoritmo robusto de restauración facial diseñado para trabajar con fotos antiguas y rostros generados por IA. Funciona como un modelo Image-to-Image, mejorando la calidad de las imágenes y restaurando detalles en los rostros. Puedes ejecutarlo en Colab para mejorar videos, fotograma por fotograma, y obtener resultados de alta calidad./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/uil_vwAhs1M"),'
            '("Colab FPS RIFE 2023","video", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEif8rPGNAHePqrpOSg6b_O6srfZ0r1aWsRp4dx4_qqi0pSz-GopeMwXYMDU1Y1nP7mwEtZxflqrRP9vvERB153cNBNhm4-lo-o18XhsTwqakHCNRh6V15GqXlZ9gOvx22LZp5rpk_mTCtkIhDRtMyYfRtSHtiq_yjjHdZErwMtyJzaDxDcJXMkvJc_W","https://colab.research.google.com/drive/1-Cxa_p8oTiflduqOJMCzSpOLxGzIGhTF", "Puedes cargar tus videos en Colab, configurar los parámetros de interpolación (como el factor de interpolación) y ejecutar el cuaderno. RIFE generará los fotogramas interpolados para ti. FPS RIFE Colab es una herramienta útil para mejorar la calidad de tus videos, ya sea para crear cámara lenta suave o simplemente para mejorar la apariencia visual./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/hXPyOllEIhc"),'
            '("Colab FPS RIFE 2022","video", "Online Colab", "https://blogger.googleusercontent.com/img/a/AVvXsEgYEj6nzS4XkjqvMkFZ6PU9BFo58C2UjSJHb4rRK7Tc1bOxQkEikAnp1b0QIAK8kBwSPBbfugXTdQYr8Pb6TbnHeOswJwhn9neCUcH8FZZvzwHUeV1k0cxCCXuyIIS5X80WMcufueZMI7X8WlCiD33_lcySeKWnVYpOz2xOb4g0fc5-yxM3ApWzWyvk","https://colab.research.google.com/drive/1a6NnAN_sPBiFMp3HEZgknRbQAulkohkc", "Es una técnica que crea fotogramas adicionales entre los fotogramas originales de un video. Esto mejora la fluidez y la calidad visual de los videos, especialmente cuando se convierten a cámara lenta. Puedes probarlo en un cuaderno interactivo alojado en Google Colab que te permite aprovechar el poder del algoritmo RIFE para interpolación de fotogramas en videos. RIFE (Real-Time Intermediate Flow Estimation)./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/crwLKp_yW6U"),'
//text
            '("Meta Llama3 8B","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgwlg_HdXaiPuEm_p2XDWTBeWjW4tveMZdnpLZZD25gFjpZqn5ynAOmlRA-MCNpYPtMdAzclDPxonNT27ODDNqLf9nrWGTA4ABVswe_yf5QBMTd0-Fb3TFuBd-bNwWNUD8cOfuEI1Zmc8atDuxoH70gDrgv-MCUsD0gt-k8CbTo7BALMrq1ZGug8gP5", "https://huggingface.co/spaces/ysharma/Chat_with_Meta_llama3_8b", "Llama3 es una de las mejores modelos de lenguaje de código abierto, con una longitud de contexto de 8K y soporte para 30 idiomas. Lo más sorprendente es que Llama3 genera imágenes en tiempo real mientras escribes tu consulta. El avance de la generación se actualiza con cada carácter que ingreses. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("perplexity","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgtvWMMaMzfKXXRPlGy23gCMhRBffdsBjNNRn3ON2_wIrBQN_RNlDZgyIIvrv5pHY9G7YIkYXnOFZjt54DbU71no99HEB9nri6aTgxpHi5m37GBmcagFM88pWROWmbZCyBr1X6nKouZ73ZncMiJnJJIn3dGf8ieAeghessePTp-_EhtgwC5urZOizSJ", "https://www.perplexity.ai/", "Es una plataforma que combina las capacidades de un buscador conversacional con inteligencia artificial generativa. Utiliza modelos de lenguaje avanzados para proporcionar respuestas precisas a preguntas complejas.  \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Copy.ai","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgSYTnEwCS3izvhBSamwumhLN8Ie42lag24en-ST0M6dacYIBF6noxL_Oe4Ppohzp2vjtZK_jLmNsX22DLUGIy_J9d1VpzgC1PNeHVh-BhIvaxo7s3FMtbxeF3nOqTRQoecAvkvBr5ixMQkVHqN2_pCrVIToR9Nf7C3saRwQVLpcsEweGDAf4RQyYX4", "https://www.copy.ai/tools", "Es una plataforma innovadora que utiliza inteligencia artificial para impulsar la creación de contenido. Con una red neuronal avanzada, la plataforma aprende de ejemplos de texto de alta calidad y patrones, resultando en algoritmos capaces de generar textos atractivos y altamente efectivos1. Ofrece una variedad de herramientas de escritura de IA que facilitan la creación de contenido para diferentes plataformas y propósitos. Ya sea que necesites un pie de foto para Instagram, un correo de marketing, una descripción de producto, una entrada de blog o un texto de ventas, puedes utilizar las generadoras de escritura de IA gratuitas de Copy.ai para obtener resultados en segundos./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Parler-TTS 🗣️","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjrynv1jwwvFY9aW5mgXFK48OQC14deql09Z7_IS-E_DiBijkhGlg19jfZhzMEzLN0Gko4Mc5BsMhfeqA3wRm60qVxLlGxrEUDFHljjqbhtsmdBh4ByEjxtwLSLdebIUc2dp2Nrl7ZOOPvaVmz-_wQE7CGrLGzqgHECRgTIBDEn7DO0YYTbg8OpDPlZ", "https://huggingface.co/spaces/parler-tts/parler_tts_mini", "Puede generar habla de alta calidad y natural con características que se pueden controlar mediante un simple prompt de texto (por ejemplo, género, ruido de fondo, velocidad de habla, tono y reverberación)/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Writesonic","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiGPIQBGFVg0YDW5-xA1Jd4dDvHo3itnzGiuLIJXUAudJ3NUUKYsVduGXLKuFlTpnXvldJqN6IBC5gTKh__OucSKiiz0mauoquKcfaBVZxIigw6rKourSHUc_P5xtULLzfXUtW9HrE2lcU4kRMsbUZ5FLS2cyCE79fFX4gbDldkvQKM1p9AuOoQ6-9G", "https://writesonic.com/ai-article-writer-generator", "Facilita la creación de contenido optimizado para SEO, como artículos de blog, descripciones de productos para comercio electrónico, anuncios para Facebook y Google, y contenido para Shopify. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Summarize Tech", "text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgCg6GEhAydb5SOv303vUjOMDlsUOrMOgVXQA67ysAsCvbEfv9h2iRtYEU52oaeyjiZuLewufmPHXF8qLllx6tAN7qlullxpxLYrekFbNGzay4sOjoz2QItVC5-MihArlZaqKTpJ0hN0OgJ21gaj74-Ydo9ze9GgO1fPZXO6VwCsMAzw6RA7MjnNmsD", "https://www.summarize.tech/", "Resume videos de YouTube rápidamente con IA. Produce un resumen escrito que incluye marcas de tiempo y una breve descripción de lo que se dijo en el video. Los usuarios pueden proporcionar la URL de un video de YouTube, y la herramienta utilizará la IA para generar un resumen del contenido del video./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Grammarly","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEiJ8ms4dGFujPcb5Q99v33vowZu87K91omtc-fBbT-VtfOjaEw6xzq8zMgNql_ShHJm3A7Go0zIUrPd2reKpxei3u7tNDuyKa4-0o0V6J2SJTgkpPvKKArFlJszEkB0ykOJLj8sI4T5u4CgYPWDp4EAaMRmrdOYCnGD47aojbhjZ8woaA3XYCrJbGCO=w945-h600-p-k-no-nu", "https://www.grammarly.com/grammar-check", "Corrige textos con IA. Grammarly puede generar texto automáticamente para ayudarte a escribir correos electrónicos, artículos, informes y más. Puedes utilizar esta función para obtener ideas o estructuras rápidas para tus documentos./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Quillbot","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEia1RJsd9iD1_AXPWR_q-shO6T3a8l-RrIW5lmg4Fn0NHIH_j4KBmVRWe5TnT6maj8kOF0Ya_D6b3TbTQuX62NYqFdBAB96LPsX5NDKkSgtcMJzXUawwUYwn8No-KBo5k_e7DuigxE48Jv7xapmgDS03wdU2qyzu8IK29nMMkiZGK3lhH-xry2L1Q8Q=w945-h600-p-k-no-nu", "https://quillbot.com/", "Hace indetectable los textos de IA. Parafrasea cualquier texto que haya sido generado con IA. Se ha diseñado para hacer que el proceso de redacción sea más eficiente y efectivo/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Copilot","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhJqTfkZe4Nzi8CX-KSUdwDVQ_u9HcpN6wICd8-ZMMuj84O3gM9rOlfO-B_tABzcg1RUjYRTsSpuQs3Lk9gK91BO9tjKiiwwnxPgJAvAc-JHJni57BWfBrF06Mg1gbl9s3kBX67zB7GhJDHURbQGGRJzmtKELFQAUiV2OYeoc8Qwqt9YQ6TO5efWiM9", "https://copilot.microsoft.com/", "Es un asistente de inteligencia artificial (IA) que ofrece soluciones innovadoras en la nube de Microsoft. Su objetivo es mejorar la productividad, creatividad y accesibilidad de datos mientras garantiza características de seguridad y privacidad empresarial. Puedes experimentar Microsoft Copilot en Microsoft Edge o Chrome en Windows y Mac OS. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("ChatGPT","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjNjrA5VZo22spD589VxGv0JsmO6sl6BUFtRSBuSg_BIVL6F1mhvDbOZGoNxxAnKXVGutR1EUXwj6qBzLpeAmAOpkRmRdx-9w8FNnDruEp0IjMZYIoLrUi-wA4kei_sFhKvyWdK0ZP85boJUh9EgeUmI_pQUIBbuovhdQFtZK_FklWQ1z7cRx5jmcy-", "https://chat.openai.com/", "Desarrollado por OpenAI, es un sistema de chat basado en el modelo de lenguaje GPT-3.5. Con más de 175 millones de parámetros, es capaz de realizar tareas relacionadas con el lenguaje, como traducción y generación de texto. Puedes interactuar con él en formato de conversación vía texto y aprovechar sus capacidades de respuesta basadas en contexto y conversaciones previas. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/5e_u0mbecQ4"),'
            '("Gemini (Bard)","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhII2Pi43r0IFWCJwEeXf0nyFoJnYWR1fw3jZVyHNe8pJ0zxTTN1dqPN01S3FbGGE2XzHwKqwIMmcxFc41MGCEqk7kJ3a4GOiL4J-T1IWGD8UI-sXwVB4qBDnxi6f09UvGI8zXq8zhGufd-fgmVmNui8tXf1WV3C7L7wKLTFkT_mrcDbfYymCQ6lPTq", "https://gemini.google.com/app", "Anteriormente conocido como Bard, es una plataforma impulsada por inteligencia artificial (IA) de Google. Ofrece herramientas para escritura, planificación, aprendizaje y másGemini Pro y Gemini Ultra son sus modelos avanzados, diseñados para mejorar la experiencia de los usuarios en tareas creativas y productivas./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Cleverbot","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEh-smGbxMNZb67xU-dxDQ0a-aERJaVdNH3__kNb_gg4E4vqj42hg4tU6Rd2AGNmNuXJY89PuCYc7RC7N_cfX2IqhTEm2DnPuvjigGHCxIpv3-5as60z-Gd304X2rZ6WwjIVhVgyec_DP332XyAIA3MNT-rwyszEO9ZCv1MV0sEXVYUg-U7kO_7gt63N", "https://www.cleverbot.com/", "Es un sitio web y una aplicación que te permite chatear con una IA que afirma tener cierta inteligencia real. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Akinator","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEj807hn3oZu1p3riY1wKTJNOVyJijiyZsEhG5vCvwj_5ARsRLhSoL86g1xpR9aNlGYyc7rWGsbAs11lYBKWEE_lk8a5MAkkeGERZM_wwhMI50l6Ae2ZRaR4jTtl2r2vVCWqol_i7Aq9fEvErk_l3x1_2xeE_9W77pODJjHzQsxoQIvNBK_3tNFN04fa", "https://es.akinator.com/", "Es como un genio lector de mentes. Piensa en un personaje real o ficticio, responde algunas preguntas y Akinator intentará adivinar quién es. Es una forma divertida de interactuar con la IA./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Namelix","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgVzC8Gi8ituahYOKj0MYLTe4W-Wr41r8eLhlOgdX9QCYKE_oCWzHTpb6wTW076ypgBqjrhhxUKaGxsQ8GGJXkzcPHszJBe8e9bAuBNRCZqvrpIPeJ0aiSdX997sWYyzmG2LhYrE_vWfSynmiF1_YkFOS-dw61FrgNd36G0T6ez6wCTBv3aCwHeTHqN", "https://namelix.com/", "Genera nombres de empresas cortos, pegadizos y de marca. Puedes filtrar los resultados por palabras clave, extensión de dominio y longitud, y guardar tus nombres favoritos para uso futuro. Namelix utiliza un potente modelo de lenguaje AI para generar nombres. Además de generar nombres, puedes explorar otras herramientas similares para la validación y construcción de sitios web./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Notion","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgUrDDqFDubbicdD25Y509ig1nAxTPenK9eBCAMyTqmpH8xBFGDDdTwCf-jZX-y1spi0S-cu7Gqenxp1vGrxuV5m2KazbjQxusA-bnXAHeS2gLD_g7S7DvAZ5X2MwpeG3HsNGukrnlpndUiwMvdXDNPw7eQgLMO8jeCdY4Ne0-pQwJ_Inlgjci7_LLY", "https://www.notion.so/", "Herramienta de asistencia basada en inteligencia artificial que se integra en varios productos de Notion, como documentos y hojas de cálculo. Utiliza el mismo modelo de lenguaje GPT-3 que ChatGPT para automatizar tareas y proporcionar información./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Grammarly","text", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjmOUhKbMWMACIR_TWGDggOz8wqDcPVRvSVsIalklm2YOooCSE-ddh8_HLReGREN-04r-gyp7htD9AIW30ZFx3nmxreKP23BKaPgJyfO8R2-lIdhcXYo2Uq4dppBQIKkADt6oLb0ElMH3DReodp27A8eVdZ-WXUKOlXM9sMqMvrdQXpxLBYUKKQMOVJ", "https://www.grammarly.com/", "Grammarly es una herramienta de asistencia de escritura basada en la nube que utiliza inteligencia artificial para mejorar la calidad de la escritura. Proporciona sugerencias en tiempo real para corregir errores de ortografía, gramática y puntuación, y mejora la claridad, el compromiso y la entrega en los textos en inglés. Detecta el plagio y sugiere reemplazos para los errores identificados. La herramienta es utilizada por más de 30 millones de personas y 70,000 equipos todos los días para mejorar la corrección, claridad, compromiso y entrega de su escritura./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Tango 2","texto", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEibbPIYDpUodXYEqqwsOuU94OI1M71QUZfvyS5Bym8NGzPJGGjNvWOxRjrDAo7kIno2rzMws_aqZDdy4TVDXmTsXzufljSx-__nSCsCU1SprZ5QjlqEOj9W7saQBrkQDJ5FjxRz1gcx7hsrCbR8GXPHvJcwG6uuLDQefa2QxGeELCPYK0AvywP-D2aE", "https://huggingface.co/spaces/declare-lab/tango2", "Diseñado para la generación de audio a partir de texto. Utiliza un enfoque de difusión latente para generar audios realistas, incluyendo sonidos humanos, sonidos de animales, sonidos naturales y efectos de sonido a partir de prompts textuales. El codificador de texto utilizado es Flan-T5, sintonizado específicamente para instrucciones. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'

//audio
            '("AI jukebox","audio", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEglBt7_ztWCvs7hD3iB5vF_x74t7QD4Z73OvuYJYelAaFuhvicNI17__JR_PaiWAcL-FwXCbmPPJW9WcDg_iBZt6DxO0hAZtl3fjU28QecDfVHtbkWL61TEJaLbJFVDjLAwinWwmRuovIaU9rV9dXYayucmG0DwIRWnS34yITvZllUWO70duxwLMzmO", "https://huggingface.co/spaces/enzostvs/ai-jukebox", "Puedes generar música impulsada por inteligencia artificial. Es un campo emocionante en el que se utilizan algoritmos y modelos de aprendizaje automático para crear composiciones musicales originales./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Adobe Podcast","audio", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjCVYS-OBzoQeTsseFScAhuI3wNcrYbFEzgjFG8e40Amz1_1FDdMI-Llfn_jR2PYRoabnEB1pe3bQygzjhLOEveOpRszH2Lbzf2jpOHGWWYiWeG0ljDE3GW2bQxKV3ZbgU3duVFG7T6i01ruc-O8LgqFlVoGIbm1MfGNN9DjQImogBnoySql9geMLUS", "https://podcast.adobe.com/enhance", "Es un producto de Adobe, de uso gratuito y online. Implementa diversas herramientas de IA para mejorar la calidad de tus grabaciones de voz y podcasts. Con funciones potenciadas por IA, puedes eliminar ruido y eco de las grabaciones, ajustar la configuración del micrófono y editar el audio como si fuera un documento de texto. Además, Adobe Podcast ofrece transcripciones precisas y música libre de regalías para tus producciones. Puedes acceder a esta herramienta en línea, lo que la hace conveniente y accesible para creadores de contenido en plataformas como Spotify, Apple Podcasts, YouTube o SoundCloud./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/PebfEH-eA7E"),'
            '("Music Gen Web","audio", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhTzRIJlFVaYSLEU_-w-VWk0nkdvd7wBy_p1QAt-Ut7imyZq_yfVeXEhZtkhyxt6Qt4YZ6FdZuoZ3U-bdeKKxJFG-KKhktilLCk0o3YtB-rvi1o5n8FI-J_ZIUR6DYt3gGq-hkpilVshAn0yBCveuYHzyJOoaSbNP-P_aX_Ab4nYsrySUnJvOe3jGRq", "https://huggingface.co/spaces/Xenova/musicgen-web", "Permite la generación de música directamente en tu navegador utilizando Transformers.js. Todo se ejecuta 100% localmente, lo que significa que no se realizan llamadas a una API externa. Escribe el prompt de texto y comparte tu musica./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Moises AI","audio", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjTJNhnR2dU_jY_j54XPWQt_S_OzWcETteDkv5xMErhPyTW4J5evOC73XZHItCgv7rQusCtEr3fQJ588VxqIhWr_k58XSa8oieX3sUEXfIwocU-6xE13qQEQDazbDMYJOrwASXyOIWlsh4SaTZZqgwLGe82vJW9YIbNwzjfhrIrMgdf0qPgSMwySexw", "https://studio.moises.ai/", "Permite practicar, eliminar, aislar y ajustar cualquier canción utilizando inteligencia artificial (IA). Puedes tocar junto a tus artistas favoritos, modificar la velocidad, el tono y el metrónomo, y descubrir los acordes y las tonalidades en cualquier canción123. Además, Moises ofrece una experiencia completa para músicos, desde separar voces e instrumentos hasta personalizar tus pistas y remezclar canciones con la potencia de la IA. /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "https://youtu.be/PebfEH-eA7E"),'
            '("Kits AI","audio", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEj6OSkrF4de4tBEy6SRazkfrKu-kj3ZgJIXU9MQM1nJKQH2DLFLhh8ykn3wRIKb-0wVKwDJJUtWaq7GUFLvGflPRbeLyoX7Y5emnHKxoDyeMZclx7oXPWvis_Q_-hDyrZ19dYRVLEHvc0XS8kt7ZTOfV-OuuuxLn6gIkDhV_KTC3IrgABhG0c4ziX9j", "https://app.kits.ai/community-voices", "Es una plataforma de herramientas musicales con inteligencia artificial (IA). Ofrece funciones como voces perfectas en casa, clonación de voces y acceso a modelos de voz con licencia oficial. Ideal para músicos y productores que buscan mejorar su música utilizando la IA . /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Mubert","audio", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgqFIpLfVeefqDCPudw3_8UBS_SDIQG-jM5tqhtjA1Mx9X0tAQBhjdIBhKIyekgGOlbuzRsOh7q8qUsbqXZn-ieJJoUvmy7fdbeQD24Plg1wJFJCgpTSseZzuahAuxIjXdEQp0HVhh_mp5MO0Bwg7t_8Vhu2yz8GiDCbfufAPnj0iqEe-PyfePTFYKb", "https://mubert.com/render", "Es una plataforma avanzada impulsada por IA que permite a los usuarios acceder instantáneamente a música de alta calidad. Ofrece una extensa biblioteca de música generada por IA, revolucionando la forma en que se crea, comparte y experimenta la música en varias plataformas digitales./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Lalal","audio", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEh8JA-NLe8NE4MKtL8EEEjJe7EsJcV3ALyOgIfUpMQmXntDajVtTcHRgjj7JQBKpOeDzfvR3luA9i_v1z9Af5CZT-zqVUaiudT-McsGFyN0kwPl9LVEAB3tSHm3mRckHsZYibIgxUY9pFmfQ1R_5sObK2ZdTEZeZo7oNV6zIEqrmD8KU3raEQOlyvQa", "https://lalal.ai/", "Se especializa en la división de alta calidad de stems. Utiliza tecnología avanzada de IA para facilitar la separación de componentes de audio como voces, pistas instrumentales, baterías, bajos y más, sin comprometer la calidad de la pista original./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'

//code
            '("OpenUI Fly Dev","code", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjEeUKsy-3qPWor4x-tCd2m3Uqze7J3ndM0l8JjY0Ct-8i78Jc8STLLmTk_n0ZS73zssTSAV528r70lWxLkY0ze-ityLdJkokCQwwcpf-i5OASReLrY_wKaitChgQmCuXnVp2jbgGotHm8dTWAbAf20geaCgnoQ_2fpBIoTe92_16-ytAgEU672eY7e=w945-h600-p-k-no-nu", "https://openui.fly.dev/ai/new", "Convierte capturas de imagen en codigo programable. Permite convertir el codigo a varios lenguajes y tecnologias/n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("AI Website Builder 10web","code", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjN7O_vVdaj8TM3KZnoyw58jgLIOZMBqUENQha9_T27sEWxfdVUMM0qWzKndz3xcHMCwDK9OhNfFoHDJPO5nFUbtezmjd7SQzpqYrRcU_2lY7Ggb1ctsFDTIhBAOtzdxg57ppTxZXahBPjnYe2So0I9M6ZBVMIxB0zw1SLO8eRS_L3BcpiA-MV1Pwk2=w945-h600-p-k-no-nu", "https://10web.io/ai-website-builder/", "Construye tu sitio web en 1 minuto con inteligencia artificial. Puedes describir tu tipo de negocio, nombre y detalles en un par de palabras. Deja que el sitio use IA generativa para crear un unico y personalizado sitio web con contenido e imagenes./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Website Builder - Durable","code", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjFVhRLNiRnz3SmCXX3yl7ZyJBn2AnuPgkMIqQvaOiQ9dh0tX7VMyI0csoDxHbg9j0P3Q7yAALh6M99tl4vYWWaM-8tSDymHOzN7KHnGpovv3f_nqTOWEeV0t-BozgkevymmOfIqQca0lX2L5-f16v_TT9vztwR1phtRrwl1DNboXONprZ2G5qus_7o=w945-h600-p-k-no-nu", "https://app.durable.co/website-builder?skipIntro=true", "Genera un sitio web en 30 segundos con solo 3 palabras. Esta plataforma es un editor de IA poderoso para crear contenido para diseño gráfico, consultoria, copywriting, tutoria, entre otros campos./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'

//number
            '("Math GPT Pro","number", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEh48frIL4fjo8fR0ym1vl1llT6DriIxyIgD7oPvxtQCDwAbKkl0DaJ4rk0jAB3i95wsNIGnvGlJxEB5u-NOxEZYzIyQni5JaoMeFats_MQqPRV0FuI5ZRYL2aU6WZJDyYgRV6snycojdOzp1gsXxO6Sfhzq37cuRXhbTfy3eqSoWS21FHzDHQAcV-kg", "https://mathgptpro.com/app/session?u=0", "Math GPT Pro Resuelve problemas matemáticos avanzados Math GPT Pro es una herramienta de IA que ayuda a resolver problemas matemáticos complejos. Puedes subir una imagen de tu problema y recibirás una solución detallada al instante. Es ideal para estudiantes y profesionales que buscan una guía rápida y precisa en matemáticas. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", ""),'
            '("Tutor Hix","number", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEhQmBk2VP4QtPcVSJbqO73W4mIpldcbYZJBxY7I8qomWNazNLgx8VmU7abiFNxI4CugpRh8-LQxaLBoEC3YfcaLGCDtLSuxrb-y6GKCi2JQcPAPjkRBiHkc5WEuiqoCJHOIGyNWxBUoupsnZ7uieUkGrF6KGLK7zK5nlwDlJ8nx-qaQlRkM2RhlQq3o", "https://smodin.io/omni/physics", "Ayuda con las tareas de matemáticas Tutor Hix es un asistente de IA para tareas que ofrece soluciones paso a paso para problemas matemáticos. Con solo subir una imagen o escribir tu pregunta, Tutor Hix analiza y proporciona respuestas detalladas, facilitando el estudio y la preparación para exámenes. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Physics AI solver","number", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEg_S8aNj_wA5EMvJxpWY9yWi5DrCc19_wKxcfNhgFPS7taUatQQ6hIR0-uaZIp67SWeY6wvalkv84sbJbpdwdRMmCxVeXswqeMzGVwOZ2ioRj7UNWU7z2XFzHC8Qk2T_t31J3gP3Cu8Lgh3bvrTPdEqdLKioj1tZT0TUPwqYdy3pZk08FBZQDtNIMDi", " https://smodin.io/omni/physics", "Physics AI Solver Resuelve problemas de física con IA Physics AI Solver de Smodin es una herramienta de IA diseñada para simplificar la resolución de problemas de física. Introduce tu problema y la herramienta generará soluciones paso a paso en segundos, lo que es muy útil para estudiantes que buscan entender mejor los conceptos de física y mejorar en sus tareas. \n\nNo es necesario iniciar sesion ni registrarse. Como nos gusta, directo al grano./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'

//other
            '("GitMind","other", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEh28DP_OHv-vVW3XCkC8arbHKwjN3PvoZmPD9qWitKz09vFi87BkqePLT0QHsp7VSMRLHKJjr1zNqCK-Lyx0bRcWSQCtpAFNLd7E3yEh6ct9Dzxsb31oCUwynLa-g72OQhEtpf3qA9RModPN21IR_Ka4E6WCUCM_O5tM4cwyyzZMyBKLjEp-HjbWBbS=w945-h600-p-k-no-nu", "https://gitmind.com/app/templates?lang=es", "Mapas mentales y lluvia de ideas impulsada por IA. Permite crear y colaborar en mapas mentales en tiempo real, así como diagramas de flujo, organigramas, diagramas UML y más./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Tome AI","other", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEjp6MXL75Q3ldpiP9mUrNq_RQgFg3iLdpUbq_hh_T2zAiP2Av4cxw8Q2KIii3nSfoGbWbvVnmHH2EvHJ8sdK1pob3XvNWLcaT8YMBKCliufvQHxA7rJTJHqHCSYi8JNEpBSmFV4LzFt0CzGbNg2_YBqGRRAueXYFTjhST5c40_L2vKrVF9iTwjj8Rto=w945-h600-p-k-no-nu", "https://tome.app/ai", "Crea tus presentaciones con inteligencia artificial. Utiliza la IA para realizar presentaciones y proyectos en formato storytelling /n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"),'
            '("Simplified","other", "Online", "https://blogger.googleusercontent.com/img/a/AVvXsEgdlYUQu5Zjkkil8oir3PRJ1hHvGGcyhG1ieevfxem4h_uADX6SXqYhitwDfGICfsz5QqBmXn3JoO7Tqz9hRHlmvoaQGQralZR655e_mu98vgKEHUmy64mYI6yHGyMIHSm3xhAkXbyPBY1TbDXzJaWdUnpgEdyYWRh7aN6s0MMmmy_Ay0vbityi1ejd", "https://simplified.com/", "Ofrece varias herramientas de IA generativa, como un escritor de texto, un generador de fuentes, un simplificador de texto y más. Está diseñado para mejorar flujos de trabajo creativos y generar contenido único./n/nEsta herramienta de IA ha sido recopilada por la app HubIA. Esperamos la disfrutes y regreses para conocer las demás IAs que tenemos para ti.", "url_tutorial"'
            ');';
        await database.execute(addIA);
      },
      version: 1,
    );
  }

  Future<List<IA>> getImgByCategory(String category) async {
    final db = await initializeDB();
    final result = await db.query(
      'access_ia',
      where: 'category = ?',
      whereArgs: [category],
    );

    var list = result.map((e) => IA.fromMap(e)).toList();
    list.shuffle(Random());
    return list;
  }

  Future<List<IA>> getIAByCategory(String? category) async {
    final db = await initializeDB();
    final List<Map<String, dynamic>> queryResult = await db.rawQuery(
        'SELECT * FROM access_ia WHERE category LIKE ?', ['%$category%']);
    return queryResult.map((e) => IA.fromMap(e)).toList();
  }

  Future<List<IA>> getIAByPalabraClave(String? palabraClave) async {
    final db = await initializeDB();
    final List<Map<String, dynamic>> queryResult = await db.rawQuery(
        'SELECT * FROM access_ia WHERE name LIKE ?', ['%$palabraClave%']);
    return queryResult.map((e) => IA.fromMap(e)).toList();
  }

  /* 
    //PARA IMPLEMENTAR EL METODO getIAsByCategory()
    List<IA> IADeArtes = await getIAsByCategory('Artes');
    List<IA> IADeCocina = await getIAsByCategory('Cocina y alimentos');
    List<IA> IAAgropecuarios = await getIAsByCategory('Agropecuario'); 
  
  */

  Future<IA?> getRandomIa(String category) async {
    final db = await initializeDB();
    final List<Map<String, dynamic>> queryResult = await db.rawQuery(
        'SELECT * FROM access_ia WHERE category like ?', ['%$category%']);

    if (queryResult.isEmpty) {
      return null;
    }

    final int randomIndex = Random().nextInt(queryResult.length);
    return IA.fromMap(queryResult[randomIndex]);
  }

  Future<int> getTotalIasInCategory(String category) async {
    final db = await initializeDB();
    final List<Map<String, dynamic>> queryResult = await db.rawQuery(
        'SELECT COUNT(*) as count FROM access_ia WHERE category like ?',
        ['%$category%']);

    return queryResult[0]['count'] ?? 0;
  }

  //CRUD IA's Favorite:

  Future<void> addIAtoFavorites(String nameIa) async {
    final db = await initializeDB();
    await db.insert(
      'favorite_ias',
      {'name': nameIa},
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  Future<List<IA>> getFavoriteIAs() async {
    final db = await initializeDB();
    final List<Map<String, dynamic>> queryResult = await db.rawQuery(
      'SELECT * FROM access_ia WHERE name IN (SELECT name FROM favorite_ias)',
    );
    return queryResult.map((e) => IA.fromMap(e)).toList();
  }

  Future<void> removeIAFromFavorites(String nameIa) async {
    final db = await initializeDB();
    await db.delete(
      'favorite_ias',
      where: 'name = ?',
      whereArgs: [nameIa],
    );
  }

  Future<void> deleteOldDatabases() async {
    for (int i = 1; i < 2; i++) {
      String dbName = 'ias_$i.db';
      await deleteDatabase(dbName);
    }
  }
}
